### PR TITLE
Logging

### PR DESCRIPTION
**Pull request by ryaneberly**
@nitram509 ,
   Here is a PR that adds the ability to log the screens from the session to an HTML file.  Take look, see if this is something we can pull into the master.

image

The output looks like:
image

### CODE REVIEW

**Comment by nitram509** [comment]
Ryan,

thank you for this PR.
This is an interesting feature, where I hesitate to built it into master, because I don't see a use case.
What problem does it solve?

Kind regards
Martin

**Comment by ryaneberly** [comment]
Hi Martin.
   One of my colleagues has been using it heavily for
documentation/tutorials.  It beats taking a screen shot one at a time.

**Comment by ryaneberly** [comment]
I am fine with leaving the functionality out of the trunk, if you don't see the usefulness.  Can we somehow incorporate the additional hooks that it depends on?

I thought including that logging feature w/ the PR would justify the hooks.  But I'd rather like to get to a point where the changes required are included in the main tn5250j trunk.  I don't want to maintain a fork :-)  The important thing is the hooks -- basically some additional listener support.

From the hooks, I can get the logging and the test driver as add-on projects/libraries no problem.

**Comment by nitram509** [comment]
Hi Ryan,

now I understand the need for the hooks.
I also see the value for your team mate, but right now I won't accept it for master branch.

Regarding the hooks I'm see more value, also for other user to extend tn5250j to their needs.

Regards
Martin

**Comment by ryaneberly** [comment]
Hey Martin,
    If it sounds like a good idea to you, I will make a PR consisting of
just the hooks.

Thanks!
- Ryan

**Comment by markvanscyoc** [comment]
I am Ryan's coworker and have benefited from the ability to record the screens and actions taken. Here are a few examples of potential uses.

- Capturing screen shots for creating training documents.
- Capturing screen shots when testing new processes. (We used this option to record steps taken when switching to a backup system. It enabled us to review problems we encountered.)
- Capturing screen shots for auditing User IDs with system level change authority.
- Capturing screen shots for system values for auditors. (This was a frequent process at my previous job at a publicly traded company.)

**Comment by ryaneberly** [comment]
The smaller PR is here:
https://github.com/tn5250j/tn5250j/pull/19

**Pull request closed without merging**
